# Generated by Django 2.0.7 on 2019-02-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='activities',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
