# Generated by Django 2.0.7 on 2019-02-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_auto_20190213_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='activities',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
