# Generated by Django 2.0.7 on 2019-02-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_auto_20190213_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='activities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(),
        ),
    ]
